CREATE TABLE db_test.test02 (
  id INT NOT NULL PRIMARY KEY AUTO INCREMENT,
  code VARCHARA(255),
  occupation VARCHARA(255)
);
INSERT INTO db_test.test02 (id, code, occupation) VALUES(1, "001", "会社員");

SELECT name, age FROM db_test.test01;

SELECT * FROM db_test.test01;

SELECT * FROM db_test.test01 WHERE age = 19;

INSERT INTO db_test.01 VALUES (6,"シバタ",40,null);


SELECT
  A TABLE.IMAGEID,
  IFNULL(COUNT, 0)
FROM
  (SELECT * FROM 'a' ORDER BY IMAGEID DESC LIMIT 3) AS ATABLE
  LEFT OUTER JOIN (
    SELECT
      IMAGEID,
      COUNT(*) AS COUNT
    FROM
     B
    GROUP BY
     IMAGEID
  ) AS BTABLE
    ON ATABLE.IMAGEID = BTABLE.IMAGEID
ORDER BY
 ATABLE.IMAGEID

SELECT
  ATABLE.IMAGEID,
  IFNULL(COUNT, 0)
FROM
  (SELECT * FROM 'a' ORDER BY IMAGEID DESC LIMIT 3) AS ATABLE
  LEFT OUTER JOIN(
    SELECT
      IMAGEID,
      COUNT(*) AS COUNT
    FROM
     B
    GROUP BY
     IMAGEID
  ) AS BTABLE
    ON ATABLE.IMAGEID = BTABLE.IMAGEID
  ORDER BY
   ATABLE.IMAGEID

SELECT
  ATABLE.IMAGEID, 
  IFNULL(COUNT, 0) 
FROM
  (SELECT * FROM `a` ORDER BY IMAGEID DESC LIMIT 3) AS ATABLE 
  LEFT OUTER JOIN ( 
    SELECT
      IMAGEID, 
      COUNT(*) AS COUNT 
    FROM
      B 
    GROUP BY
      IMAGEID
  ) AS BTABLE 
    ON ATABLE.IMAGEID = BTABLE.IMAGEID 
ORDER BY
  ATABLE.IMAGEID